USE cafy21573;

DROP TABLE POPULATION1;
DROP TABLE COUNTRY;

CREATE TABLE COUNTRY(CON_CODE INT PRIMARY KEY, NAME VARCHAR(30) NOT NULL, CAPITAL VARCHAR(30));
CREATE TABLE POPULATION1(POP_CODE INT PRIMARY KEY, POPULATION INT, CON_CODE INT, FOREIGN KEY(CON_CODE) REFERENCES COUNTRY(CON_CODE));

DESC COUNTRY;
DESC POPULATION1;

INSERT INTO COUNTRY(CON_CODE, NAME, CAPITAL) VALUES(1, 'USA', 'WASHINGTON DC');
INSERT INTO COUNTRY(CON_CODE, NAME, CAPITAL) VALUES(2, 'UK', 'LONDON');
INSERT INTO COUNTRY(CON_CODE, NAME, CAPITAL) VALUES(3, 'RUSSIA', 'MOSCOW');
INSERT INTO COUNTRY(CON_CODE, NAME, CAPITAL) VALUES(4, 'JAPAN', 'TOKYO');
INSERT INTO COUNTRY(CON_CODE, NAME, CAPITAL) VALUES(5, 'INDIA', 'NEW DELHI');

INSERT INTO POPULATION1(POP_CODE, POPULATION, CON_CODE) VALUES(101, 435678678, 1);
INSERT INTO POPULATION1(POP_CODE, POPULATION, CON_CODE) VALUES(102, 546734565, 2);
INSERT INTO POPULATION1(POP_CODE, POPULATION, CON_CODE) VALUES(103, 542378905, 3);
INSERT INTO POPULATION1(POP_CODE, POPULATION, CON_CODE) VALUES(104, 5123234, 4);
INSERT INTO POPULATION1(POP_CODE, POPULATION, CON_CODE) VALUES(105, 123245789, 5);

SELECT * FROM COUNTRY;
SELECT * FROM POPULATION1;


SELECT NAME FROM COUNTRY C ,POPULATION1 P 
WHERE C.CON_CODE = P.CON_CODE ORDER BY POPULATION DESC LIMIT 1;

SELECT NAME, POPULATION FROM COUNTRY C, POPULATION1 P
WHERE C.CON_CODE = P.CON_CODE AND CAPITAL = "TOKYO";

SELECT NAME FROM COUNTRY C ,POPULATION1 P 
WHERE C.CON_CODE = P.CON_CODE ORDER BY POPULATION LIMIT 1;

SELECT NAME, POPULATION FROM COUNTRY C, POPULATION1 P
WHERE C.CON_CODE = P.CON_CODE ORDER BY NAME;

