USE cafy21573;

DROP TABLE IF EXISTS ERROR;
CREATE TABLE ERROR(ERROR_MSG VARCHAR(50) UNIQUE);

DROP PROCEDURE IF EXISTS FAIL;
DELIMITER $
CREATE PROCEDURE FAIL(MSG VARCHAR(50))
BEGIN
	INSERT INTO ERROR VALUES(MSG);
    INSERT INTO ERROR VALUES(MSG);
END $
DELIMITER ;