USE cafy21573;

DROP TABLE PART;
DROP TABLE MACHINE;

CREATE TABLE MACHINE(MNO INT PRIMARY KEY, NAME VARCHAR(30) NOT NULL, MTYPE VARCHAR(30), MCOST INT);
CREATE TABLE PART(PNO INT PRIMARY KEY, PNAME VARCHAR(30), PDESC VARCHAR(30), MNO INT, FOREIGN KEY(MNO) REFERENCES MACHINE(MNO));

DESC MACHINE;
DESC PART;

INSERT INTO MACHINE(MNO, NAME, MTYPE, MCOST) VALUES(101, 'ZXZC', 'FR', 20000);
INSERT INTO MACHINE(MNO, NAME, MTYPE, MCOST) VALUES(102, 'CVFG', 'ST', 15000);
INSERT INTO MACHINE(MNO, NAME, MTYPE, MCOST) VALUES(103, 'AWER', 'RD', 7000);
INSERT INTO MACHINE(MNO, NAME, MTYPE, MCOST) VALUES(104, 'ERTY', 'AB', 8000);
INSERT INTO MACHINE(MNO, NAME, MTYPE, MCOST) VALUES(105, 'ERWT', 'CF', 9000);

INSERT INTO PART(PNO, PNAME, PDESC, MNO) VALUES(201, 'CFRE', 'CVF', 101);
INSERT INTO PART(PNO, PNAME, PDESC, MNO) VALUES(202, 'ABCD', 'AWE', 102);
INSERT INTO PART(PNO, PNAME, PDESC, MNO) VALUES(203, 'TYUI', 'NHJ', 103);
INSERT INTO PART(PNO, PNAME, PDESC, MNO) VALUES(204, 'TRYU', 'MJI', 104);
INSERT INTO PART(PNO, PNAME, PDESC, MNO) VALUES(205, 'CDFG', 'BGH', 105);
INSERT INTO PART(PNO, PNAME, PDESC, MNO) VALUES(206, 'CFDR', 'CVG', 103);
INSERT INTO PART(PNO, PNAME, PDESC, MNO) VALUES(207, 'HJUI', 'SDR', 104);
INSERT INTO PART(PNO, PNAME, PDESC, MNO) VALUES(208, 'CMVN', 'NJI', 102);
INSERT INTO PART(PNO, PNAME, PDESC, MNO) VALUES(209, 'QWER', 'WER', 101);

SELECT * FROM MACHINE;
SELECT * FROM PART;

UPDATE MACHINE SET MCOST =(MCOST+(MCOST/10));
SELECT * FROM MACHINE;

SELECT M.*, PNAME FROM MACHINE M, PART P 
WHERE M.MNO = P.MNO;

SELECT PNAME FROM MACHINE M, PART P
WHERE M.MNO = P.MNO AND MCOST<20000;

SELECT NAME, COUNT(P.PNO) FROM MACHINE M, PART P 
WHERE M.MNO = P.MNO GROUP BY NAME;
