USE cafy21573;

/*Bank*/
DROP TRIGGER IF EXISTS BANKTRIGGER;
DELIMITER $
CREATE TRIGGER BANKTRIGGER BEFORE INSERT ON ACCOUNT1 
FOR EACH ROW
BEGIN
	DECLARE DUMMY INT;
    IF NEW.ACC_NO <= 0 THEN 
    CALL FAIL('Account no. cannot be less than or equal to zero');
    END IF;
END $
DELIMITER ;

#INSERT INTO ACCOUNT1(ACC_NO, ACC_TYPE, BALANCE, CUST_NO, BRANCH_NO) VALUES(-307, 'SAVING', 12000, 105, 202);
#SELECT * FROM ACCOUNT1;
 
/*Railway Reservation*/
DROP TRIGGER IF EXISTS RAILWAY1;
DELIMITER $
CREATE TRIGGER RAILWAY1 BEFORE UPDATE ON TRAIN1 
FOR EACH ROW 
BEGIN 
	DECLARE DUMMY INT;
    IF NEW.ARRIVAL_TIME > NEW.DEPART_TIME THEN 
    CALL FAIL('Arrival time must be less than depart time');
	END IF;
END $
DELIMITER ;
#DROP TABLE IF EXISTS TRAIN1;
INSERT INTO TRAIN1(TRAIN_NO, TRAIN_NAME, DEPART_TIME, ARRIVAL_TIME, SOURCE_STN, DEST_STN, NO_OF_RES_BOGIES, BOGIS_CAPACITY)
VALUES(106, 'METRO TRAIN', '12:00:00', '12:20:00', 'SHIVAJINAGAR', 'HINJEWADI', 12, 25);
SELECT * FROM TRAIN1;
